import { v4 as uuidv4 } from 'uuid';
import  landingTailwind  from  './landingTaiwind.png'

export const projects = [
	{
		type: 'reactJs',
		title: 'Marvel Quiz',
		img: 'https://images.unsplash.com/photo-1635863138275-d9b33299680b?q=80&w=1931&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
		description:
		'A full stack App with Reactjs and Firebase for a quiz about Marvel',
		link: 'https://marvel-quiz-27f11.web.app/',
		codeLink: 'https://github.com/Sidiraos/marvelquiz-app.git',
		techStack: 'ReactJs , Jsx , Css , Sass , Firebase',
		id: uuidv4(),
	},
	{
		type: 'reactJs',
		title: 'React Audio Player',
		img:'https://img.freepik.com/free-vector/illustration-music-application-icon_53876-35882.jpg?w=740&t=st=1701939966~exp=1701940566~hmac=61dc047968553d958f9f29bc004d40d2cf059a8436ca1bcd6f44966eb954aeb9',
		description:
		'Customize audio player with reactjs , reduxToolkit and songs get by deezer Api',
		link: 'https://sidiraos.github.io/react-music-player/',
		codeLink: 'https://github.com/Sidiraos/react-music-player.git',
		techStack: 'ReactJs , Jsx , Css , TailwindCss , reduxToolkit',
		id: uuidv4(),
	},
	{
		type: 'reactJs',
		title: 'Little Lemon',
		img: 'https://images.unsplash.com/photo-1600891964599-f61ba0e24092?q=80&w=2070&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
		description: 'A website restaurant',
		link: 'https://sidiraos.github.io/little-lemon/',
		codeLink: 'https://github.com/Sidiraos/little-lemon.git',
		techStack: ' ReactJs , Jsx , Css',
		id: uuidv4(),
	},
	{
		type: 'reactJs',
		title: 'Mug Shop',
		img : 'https://i.pinimg.com/564x/99/15/ab/9915ab232003cd63f5bf09d1a1853a43.jpg',
		description: 'buy your favorite mug customized for developpers',
		link: 'https://sidiraos.github.io/mug-shop/',
		codeLink: 'https://github.com/Sidiraos/mug-shop.git',
		techStack: ' ReactJs , Jsx , Css , TailwindCss , reduxToolkit',
		id: uuidv4(),
	},
	{
		type: 'reactJs',
		title: 'Smart IDE',
		img: 'https://logowik.com/content/uploads/images/visual-studio-code7642.jpg',
		description: 'Smart front end IDE with react and redux toolkit',
		link: 'https://sidiraos.github.io/smartIDE/',
		codeLink: 'https://github.com/Sidiraos/smartIDE.git',
		techStack: 'ReactJs, TailwindCss , Jsx , reduxToolkit',
		id: uuidv4(),
	},
	{
		type: 'reactJs',
		title: 'My Books',
		img: 'https://images.unsplash.com/photo-1513475382585-d06e58bcb0e0?q=80&w=2070&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
		description:
			'A react app for searching books with google book api and add your favorite book to your list and save on localStorage',
		link: 'https://sidiraos.github.io/Book_app',
		codeLink: 'https://github.com/Sidiraos/Book_app',
		techStack: 'ReactJs , Redux ,  Jsx , Bootstrap ',
		id: uuidv4(),
	},
	{
		type: 'reactJs',
		title: 'Weather App',
		img: 'https://img.freepik.com/free-vector/lightning-element-cute-weather-clipart-vector-grey-background_53876-135906.jpg?w=740&t=st=1700825129~exp=1700825729~hmac=f25ea8d6567e9d15b84c10ab2b775d6f0768eb8eb4f3f041d35a1e4cf7e696d6',
		description: 'A simple weather app with react ',
		link: 'https://sidiraos.github.io/weather_app-react/',
		codeLink: 'https://github.com/Sidiraos/weather_app-react.git',
		techStack: 'ReactJs, Jsx , Css ',
		id: uuidv4(),
	},
	{
		type: 'reactJs',
		title: 'GeoData App',
		img : 'https://clipart-library.com/images/zTX5nejpc.jpg',
		description: 'Find Informations about European Countries with GeoData Api',
		link: 'https://sidiraos.github.io/geodata-react-app/',
		codeLink: 'https://github.com/Sidiraos/geodata-react-app.git',
		techStack: 'ReactJs, TailwindCss , Jsx ',
		id: uuidv4(),
	},
	{
		type: 'reactJs',
		title: 'Pomodoro react App',
		img: 'https://img.freepik.com/free-psd/alarm-clock-icon-isolated-3d-render-illustration_439185-12340.jpg?w=740&t=st=1701528665~exp=1701529265~hmac=b85e98e9528f76b6cb67e0e4468f06fcea8044a2b25a9e201848085efbf17c70',
		description: 'Pomodoro react app with react hooks , redux toolkit',
		link: 'https://sidiraos.github.io/pomodoro-react/',
		codeLink: 'https://github.com/Sidiraos/pomodoro-react.git',
		techStack: 'ReactJs, TailwindCss , Jsx , reduxToolkit',
		id: uuidv4(),
	},
	{
		type: 'reactJs',
		title: 'Gradient Maker',
		img : 'https://i0.wp.com/css-tricks.com/wp-content/uploads/2020/11/css-gradient.png?fit=1200%2C600&ssl=1',
		description: 'Create Gradient background and copy it to clipboard',
		link: 'https://sidiraos.github.io/gradient-maker/',
		codeLink: 'https://github.com/Sidiraos/gradient-maker.git',
		techStack: 'ReactJs, TailwindCss , Jsx , reduxToolkit',
		id: uuidv4(),
	},
	// pure tailwindCss project
	{
		type: 'tailwindCss',
		title: 'Landing page',
		img: landingTailwind,
		description: 'Landing page with tailwind',
		link : "https://sidiraos.github.io/Landing-page-tailwindCss",
		codeLink: 'https://github.com/Sidiraos/Landing-page-tailwindCss.git',
		techStack: 'Html , Css, tailwindCss',
		id: uuidv4(),

	},
	// javascript vanilla others projects
	{
		type: 'vanillaJs',
		title: 'Porsche Car Landing Page',
		img: 'https://images.unsplash.com/photo-1617654112329-c446806d40e8?q=80&w=1995&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
		description: 'A Wonderful landing page for a Porsche car',
		link: 'https://sidiraos.github.io/car-landing-page-animation/',
		codeLink: 'https://github.com/Sidiraos/car-landing-page-animation.git',
		techStack: 'Vanilla JavaScript , Html , Css',
		id: uuidv4(),
	},
	{
		type: 'vanillaJs',
		title: 'Audio Player',
		img: 'https://cdn.pixabay.com/photo/2017/05/09/10/03/sound-2297768_1280.png',
		description: 'A custom audio player with vanilla Js',
		link: 'https://sidiraos.github.io/Audio-Player-App/',
		codeLink: 'https://github.com/Sidiraos/Audio-Player-App.git',
		techStack: 'Vanilla JavaScript , Html , Css',
		id: uuidv4(),
	},

	{
		type: 'vanillaJs',
		title: 'Calculator App',
		img: 'https://cdn.dribbble.com/users/166931/screenshots/1117179/rebound.png',
		description:
			'A calculator app that can add, subtract, multiply and divide with react',
		link: 'https://sidiraos.github.io/Calculator_App/',
		codeLink: 'https://github.com/Sidiraos/Calculator_App.git',
		techStack: 'Vanilla JavaScript , Html , Css',
		id: uuidv4(),
	},
	{
		type: 'vanillaJs',
		title: 'Air Quality App',
		img: 'https://i.pinimg.com/originals/06/c4/f7/06c4f70ec5931e2342e703e8a3f0a253.png',
		description:
			'An App wich measures the air quality that can fetch the air quality of any city with vanilla Js',
		link: 'https://sidiraos.github.io/Air-quality-App/',
		techStack: 'Vanilla JavaScript , Html , Css',
		codeLink: 'https://github.com/Sidiraos/Air-quality-App.git',
		id: uuidv4(),
	},
	{
		type: 'vanillaJs',
		title: 'Infinite Scroll',
		img: 'https://www.creativefabrica.com/wp-content/uploads/2023/01/28/Infinity-logo-and-symbol-vector-line-Graphics-17822479.jpg',
		description:
			'Infinite Scroll with generate free image unsplash api when scrolling down the page',
		link: 'https://sidiraos.github.io/infinity_scroll-App/',
		techStack: 'Vanilla JavaScript , Html , Css',
		codeLink: 'https://github.com/Sidiraos/infinity_scroll-App.git',
		id: uuidv4(),
	},
	{
		type: 'vanillaJs',
		title: 'Typing Game',
		img: 'https://thepurposefulnest.com/wp-content/uploads/2020/04/Typing-Games-for-Kids-.jpg',
		description:
			'Try To Type fast on the keyboard the random quote generate by Api and get hight score before 60s',
		link: 'https://sidiraos.github.io/Typing-Game-App/',
		techStack: 'Vanilla JavaScript , Html , Css',
		codeLink: 'https://github.com/Sidiraos/Typing-Game-App.git',
		id: uuidv4(),
	},
	{
		type: 'vanillaJs',
		title: 'Qcm Quiz',
		img: 'https://images.unsplash.com/photo-1539628399213-d6aa89c93074?q=80&w=2070&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
		description: 'Qcm Quiz with vanilla Js',
		link: 'https://sidiraos.github.io/petit_quiz_JS/',
		techStack: 'Vanilla JavaScript , Html , Css , Sass',
		codeLink: 'https://github.com/Sidiraos/petit_quiz_JS.git',
		id: uuidv4(),
	},
	{
		type: 'vanillaJs',
		title: 'Wikipedia Search',
		img: 'https://images.unsplash.com/photo-1566396223585-c8fbf7fa6b6d?q=80&w=1898&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
		description: 'Wikipedia Search with vanilla Js',
		link: 'https://sidiraos.github.io/API_wikipedia/',
		techStack: 'Vanilla JavaScript , Html , Css',
		codeLink: 'https://github.com/Sidiraos/API_wikipedia.git',
		id: uuidv4(),
	},
	{
		type: 'vanillaJs',
		title: 'Linear Gradient Colors Generator',
		img: 'https://images.unsplash.com/photo-1579546929518-9e396f3cc809?q=80&w=2070&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
		description: 'Linear gradient color App ',
		link: 'https://sidiraos.github.io/linear_gradient_app/',
		techStack: 'Vanilla JavaScript , Html , Css , Sass',
		codeLink: 'https://github.com/Sidiraos/linear_gradient_app.git',
		id: uuidv4(),
	},
	{
		type: 'vanillaJs',
		title: 'Pomodoro App',
		img: 'https://images.unsplash.com/photo-1508599804355-8ce5238b44b1?q=80&w=2070&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
		description: 'Pomodoro App ',
		link: 'https://sidiraos.github.io/pomodoro_App/',
		techStack: 'Vanilla JavaScript , Html , Css , Sass',
		codeLink: 'https://github.com/Sidiraos/pomodoro_App.git',
		id: uuidv4(),
	},
	{
		type: 'vanillaJs',
		title: 'Card Game App',
		img: 'https://images.unsplash.com/photo-1615162818882-14d8d6330fd3?q=80&w=1974&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
		description: 'Flip card and find the matching pair',
		link: 'https://sidiraos.github.io/Card_game-App/',
		techStack: 'Vanilla JavaScript , Html , Css , Sass',
		codeLink: 'https://github.com/Sidiraos/Card_game-App.git',
		id: uuidv4(),
	},
	{
		type: 'vanillaJs',
		title: 'Password Generator App',
		img: 'https://images.unsplash.com/photo-1526374965328-7f61d4dc18c5?q=80&w=2070&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
		description: 'Generator Strong Password',
		link: 'https://sidiraos.github.io/password-generator-App/',
		techStack: 'Vanilla JavaScript , Html , Css , Sass',
		codeLink: 'https://github.com/Sidiraos/password-generator-App.git',
		id: uuidv4(),
	},
	{
		type: 'vanillaJs',
		title: 'Filter DataBase',
		img: 'https://images.unsplash.com/photo-1551033406-611cf9a28f67?q=80&w=1887&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
		description: 'filter DataBase on a dashboard with vanilla Js',
		link: 'https://sidiraos.github.io/filterable_App/',
		techStack: 'Vanilla JavaScript , Html , Css',
		codeLink: 'https://github.com/Sidiraos/filterable_App-.git',
		id: uuidv4(),
	},
	{
		type: 'vanillaJs',
		title: 'Customize Video Player',
		img: 'https://images.unsplash.com/photo-1611162616475-46b635cb6868?q=80&w=1974&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
		description: 'customize video player with vanilla Js',
		link: 'https://sidiraos.github.io/customize_player-App/',
		techStack: 'Vanilla JavaScript , Html , Css',
		codeLink: 'https://github.com/Sidiraos/customize_player-App.git',
		id: uuidv4(),
	},
	{
		type: 'vanillaJs',
		title: 'Morpion Game',
		img: 'https://cdn.pixabay.com/photo/2015/09/17/15/44/game-944386_1280.jpg',
		description: "Let's play morpion",
		link: 'https://sidiraos.github.io/Morpion_game-App/',
		techStack: 'Vanilla JavaScript , Html , Css',
		codeLink: 'https://github.com/Sidiraos/Morpion_game-App.git',
		id: uuidv4(),
	},
];
